### ISSUE TITLE
用kd加载，IoCreateDevice失败

### ISSUE THREAD

**Issue by wexiuwexiu** [FiYHer/EASY-HWID-SPOOFER#2]

**Comment by wexiuwexiu** [comment]
![1](https://user-images.githubusercontent.com/48826894/108800258-98f6f900-75cd-11eb-8297-e36816ca01d5.png)

**Comment by wexiuwexiu** [comment]
噢,原来返回值是c0000035，无法创建多个同名设备哈哈。

**Comment by FiYHer** [comment]
关闭
