### ISSUE TITLE
请问能不能修改为特定的机械码呢

### ISSUE THREAD

**Issue by Ahtaler** [FiYHer/EASY-HWID-SPOOFER#3]
有个私人定制的解压程序需要识别机械码。我进了软件里翻来覆去没看到XD
大哥辛苦了

**Comment by Ahtaler** [comment]
先点个Star

**Comment by FiYHer** [comment]
> 有个私人定制的解压程序需要识别机械码。我进了软件里翻来覆去没看到XD
> 大哥辛苦了

自己改代码呀大哥
